site_name: !ENV [SITE_NAME, 'Millennium Machines']
site_url: !ENV [SITE_URL, 'https://millenniummachines.github.io/docs']
site_description: !ENV [SITE_DESCRIPTION, 'Documentation for Millennium Machines']
repo_url: https://github.com/MillenniumMachines/millenniummachines.github.io
edit_uri: !ENV [EDIT_URL, 'edit/main/docs/']

nav:
  - Home: index.md
  - "Milo - Desktop CNC Mill":
    - Sourcing Guide: milo/bom/sourcing_guide.md
    - Printing Guide: milo/printing/print_guide.md
    - Frequently Asked Questions: milo/faq.md
    - Assembly Manual:
        - Acknowledgements: milo/assembly_manual/chapters/acknowledgements.md
        - Introduction: milo/assembly_manual/chapters/introduction.md
        - Hardware Reference: milo/assembly_manual/chapters/hardware_reference.md
        - Y-Axis Assembly: milo/assembly_manual/chapters/y_axis_assembly.md
        - X-Axis Assembly: milo/assembly_manual/chapters/x_axis_assembly.md
        - Z-Axis Assembly: milo/assembly_manual/chapters/z_axis_assembly.md
        - FMJ Assembly: milo/assembly_manual/chapters/fmj_assembly.md
        - Table Assembly: milo/assembly_manual/chapters/table_assembly.md
    - Electronics Manual:
        - Introduction: milo/electronics_manual/chapters/introduction.md
        - Install RRF: milo/electronics_manual/chapters/install_rrf.md
        - Assembly and Wiring: milo/electronics_manual/chapters/assemble_electronics.md
        - Pre-Flight Checks: milo/electronics_manual/chapters/pre_flight_checks.md

  - "Long John Toolsetter":
    - Sourcing and Print Guild: long-john/bom/sourcing_and_print_guide.md
    - Assembly Manual: long-john/assembly_manual/assembly_manual.md
    - Electronics Manual: long-john/assembly_manual/electronics_manual.md

extra:
  SITE_INTRO: !ENV [SITE_INTRO, 'Welcome to Millennium Machines!']

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - macros

theme:
  name: material
  font:
    text: Roboto
  icon:
    logo: fontawesome/solid/industry
    annotation: material/wrench-outline
  favicon: img/millennium-machines-icon.png
  palette:
    scheme: slate
    primary: red
    accent: custom

  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
